# Generated by Django 5.1.1 on 2025-07-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('memory', 'Memory'), ('attention', 'Attention'), ('speed', 'Speed'), ('logic', 'Logic'), ('language', 'Language'), ('multi', 'Multi-Domain'), ('advanced', 'Advanced Competetive Exercises')], max_length=20)),
                ('base_xp_reward', models.IntegerField(default=10, help_text='Base XP awarded for completing this game')),
                ('difficulty_multiplier', models.FloatField(default=1.0, help_text='Multiplier for XP based on difficulty')),
            ],
        ),
    ]
