# Generated by Django 5.1.1 on 2025-07-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('memory', 'Memory'), ('attention', 'Attention'), ('speed', 'Speed'), ('logic', 'Logic'), ('language', 'Language'), ('multi', 'Multi-Domain'), ('competetive', 'Competetive')], max_length=20),
        ),
    ]
