# Generated by Django 5.2.3 on 2026-07-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_multiplayermatch_multiplayerscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('memory', 'Memory'), ('attention', 'Attention'), ('speed', 'Speed'), ('logic', 'Logic'), ('language', 'Language'), ('multi', 'Multi-Domain'), ('competitive', 'Competitive')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='multiplayermatch',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Players'), ('active', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='waiting', max_length=20),
        ),
    ]
