# Generated by Django 5.1.1 on 2025-07-24 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('level_reached', models.PositiveIntegerField(default=1)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.IntegerField(default=0, help_text='Game duration in seconds')),
                ('streaks', models.IntegerField(default=0)),
                ('mistakes', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('level_reached', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('streaks', models.IntegerField(default=0)),
                ('mistakes', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('level_reached', models.PositiveIntegerField(default=1)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('best_streak', models.IntegerField(default=0)),
                ('fewest_mistakes', models.IntegerField(default=999)),
                ('most_correct', models.IntegerField(default=0)),
                ('times_played', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_scores', to='games.game')),
            ],
        ),
    ]
