# Generated by Django 5.2.3 on 2026-07-29 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_category_alter_multiplayermatch_status'),
        ('leaderboard', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gameresult',
            index=models.Index(fields=['user', '-played_at'], name='leaderboard_user_id_39b0e0_idx'),
        ),
        migrations.AddIndex(
            model_name='gameresult',
            index=models.Index(fields=['game', '-played_at'], name='leaderboard_game_id_3fad0b_idx'),
        ),
    ]
