# Generated by Django 5.1.1 on 2025-07-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, help_text="User's display name. Can include spaces and symbols.", max_length=150, null=True, unique=True),
        ),
    ]
