# Generated by Django 5.2.3 on 2026-07-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='experience',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
